import { styled } from "@styles/stitches";
import Image from "next/image";
import React from "react";
import { QUERIES } from "src/constants";
import { Para } from "src/GlobalComponents";

const FEATURE_DATA = [
  {
    image: "/images/Search.svg",
    desc: "Simply add a keyword or a term related to your business in the slogan maker search box. Wait for the magic to happen.",
    heading: "Search",
  },
  {
    image: "/images/Select.svg",
    desc: "Choose from thousands of options generated by the slogan maker that fit your needs.",
    heading: "Select",
  },
  {
    image: "/images/Stand_out.svg",
    desc: "Congrats on your new slogan. It's time to win the world!",
    heading: "Search",
  },
];

const FeaturesGrid = () => {
  return (
    <OuterContainer>
      <InnerContainer>
        {FEATURE_DATA.map((data, index) => {
          return (
            <Card key={index}>
              <Image
                src={data.image}
                width={72}
                height={72}
                alt={`${data.heading} Image`}
              />
              <CardHeading>{data.heading}</CardHeading>
              <Para>{data.desc}</Para>
            </Card>
          );
        })}
      </InnerContainer>
    </OuterContainer>
  );
};

const Card = styled("div", {
  textAlign: "center",
});

const CardHeading = styled("h5", {
  fontSize: "1.25rem",
  margin: "1rem 0 8px 0",
});

const InnerContainer = styled("main", {
  maxWidth: "1120px",
  padding: "$$sidePadding",
  margin: "0 auto",
  borderRadius: "8px",
  display: "grid",
  gridTemplateColumns: "repeat(3, 1fr)",
  gap: "0 32px",

  [`@media ${QUERIES.tabletAndDown}`]: {
    gridTemplateColumns: "1fr",
    gap: "3rem",
  },
});

const OuterContainer = styled("div", {
  padding: "76px 0 64px 0",
  backgroundColor: "rgba(20, 110, 180, 0.05)",
});

export default FeaturesGrid;
